-- Run this in your Supabase SQL Editor to create the necessary table

create table if not exists issued_books (
  id bigint generated by default as identity primary key,
  book_id text not null,
  user_id text not null,
  title text not null,
  author text,
  image text,
  issue_date timestamp with time zone default timezone('utc'::text, now()) not null,
  due_date timestamp with time zone not null,
  status text default 'issued'
);

-- Enable Row Level Security (best practice, though we are adding a permissive policy for dev)
alter table issued_books enable row level security;

-- Create policy to allow all operations (adjust for production!)
create policy "Enable all access for all users" 
on issued_books 
for all 
using (true) 
with check (true);
